networks:
  ssh-networkX: null
services:
  ssh-serverX:
    build: ssh-server/
    container_name: circleX
    cpu_shares: 10
    depends_on: syslog-server
    environment:
      SSH_PASSWORD: Password1
      SSH_PORT: 10022
      SSH_USER: sshuser
      SYSLOG_SERVER: syslog-server
    hostname: circleX
    mem_limit: 20m
    memswap_liit: 40m
    networks:
    - ssh-networkX
    ports:
    - 10022:10022
    restart: always
    sysctls:
      net.core.somaxconn: 128
      net.ipv4.tcp_syncookies: 0
    ulimits:
      nofile:
        hard: 2048
        soft: 2048
      nproc: 512
    volumes:
    - ./www-data:/www-data/public_html
  syslog-server:
    build: syslog-server/
    container_name: common-syslog
    networks:
    - ssh-networkX
    restart: always
    volumes:
    - ./log:/var/log
version: '2.4'
